#!/bin/sh
# Script for CPU usage display for status bar

cpu="$(top -bn 1 | awk '/^%Cpu/ {print int($2 + $4 + $6)}')"

case $BUTTON in
	1) alacritty --class gotop -e gotop ;;
	3) alacritty --class htop -e htop ;;
	4) alacritty -e nvim "$0" ;;
esac

echo "[CPU $cpu%]"
